# Generated by Django 5.2.7 on 2025-11-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Second_name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=2)),
                ('Tell', models.CharField(blank=True, max_length=12)),
                ('Email', models.EmailField(max_length=100)),
                ('School_id', models.CharField(max_length=10)),
            ],
        ),
    ]
